### ISSUE TITLE
Cache image on first load to avoid repeated loading of the same image

### ISSUE THREAD

**Issue by astronomersiva** [ChennaiAstronomyClub/chromapod#1]
Currently, the image is downloaded every time a new tab is opened. Should cache it so that images are loaded only once in a day saving bandwidth and the API limits.

Tried localStorage but that approach runs into tainted canvas error as APOD does not seem to have CORS enabled.

**Comment by astronomersiva** [comment]
@sid9611 :bell:

**Comment by astronomersiva** [comment]
For now, I have stored the API response in the localStorage to reduce the number of API calls. Implemented in commit 7cabee06bf9c8217f90b731a7017f1315389ce9a

**Comment by sid9611** [comment]
Ooh this is nice! I will look into it after exams :P

On Fri, Jan 22, 2016 at 8:57 AM, Sivasubramanyam A <notifications@github.com

**Comment by astronomersiva** [comment]
Sure. Also take up the ISS pass notification extension that we were talking about. Closing this issue for now as API responses and images are being cached.
